services:
  - type: web
    name: app
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile   # <- archivo, no carpeta
    buildContext: ./backend              # <- el contexto es la carpeta backend
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
