services:
  - type: web
    name: crawler-api
    env: docker
    plan: free
    dockerfilePath: backend/Dockerfile
    buildContext: ./backend        # <— ESTA LÍNEA ES LA CLAVE
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
