services:
  - type: web
    name: crawler-api
    env: docker
    plan: free
    autoDeploy: true
    dockerfilePath: backend/Dockerfile
    healthCheckPath: /health
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
